######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 23 10:50:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ndsyntax.cpp
