######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 13 12:54:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
