######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 21 06:27:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pointerdemo.cpp
