######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 14 22:29:54 2013
######################################################################

include(common.pri)

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qliterals.cpp
