######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 24 20:51:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += constptr.cpp
