######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 12 06:12:57 2013
######################################################################

include(common.pri)

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += fac.cpp
