######################################################################
# Automatically generated by qmake (3.0) Tue Jan 7 15:06:59 2014
######################################################################

TEMPLATE = app
TARGET = ssh
INCLUDEPATH += .

# Input
HEADERS += libssh2_config.h
SOURCES += ssh2_exec.cpp

LIBS += -lssh2
