######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 19 06:42:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex13.cpp
