######################################################################
# Automatically generated by qmake (3.0) Wed Jan 8 14:49:39 2014
######################################################################

TEMPLATE = app
TARGET = ssh2
INCLUDEPATH += .

# Input
SOURCES += ssh_exec.cpp

LIBS += -lssh2
