######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 26 21:50:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += complex.h
SOURCES += complex.cpp
